name: Build and Run Tests
on:
  workflow_call:
    inputs:
      upload-pages-artifact:
        required: false
        type: boolean
        default: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: npm ci
      - run: npm run build
      - run: npm run test:unit
      - run: npm run test:integration
      - run: npm run test:e2e
      - if: ${{ inputs.upload-pages-artifact }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/
