name: Deploy to GitHub Pages
on:
   push:
      branches:
         - main
jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      permissions:
         pages: write
         id-token: write
      environment:
         name: github-pages
         url: ${{ steps.deployment.outputs.page_url }}
      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
              node-version: '21'
         - run: npm ci
         - run: npm run build
         - uses: actions/configure-pages@v3
         - uses: actions/upload-pages-artifact@v1
           with:
              path: dist/
         - uses: actions/deploy-pages@v3
           with:
              id: deployment
